const authRoutes = require('./modules/auth/auth.routes');
const auditRoutes = require('./modules/audit/audit.routes');
const schoolRoutes = require('./modules/schools/school.routes');
const superAdminRoutes = require('./modules/superadmin/superadmin.routes');
const subscriptionRoutes = require('./modules/subscriptions/subscription.routes');
const studentRoutes = require('./modules/students/student.routes');
const classRoutes = require('./modules/classes/class.routes');
const subjectRoutes = require('./modules/subjects/subject.routes');
const teacherRoutes = require('./modules/teachers/teacher.routes');
const parentRoutes = require('./modules/parents/parent.routes');
const courseRoutes = require('./modules/courses/course.routes');
const scheduleRoutes = require('./modules/schedules/schedule.routes');
const roomRoutes = require('./modules/rooms/room.routes');
const gradeRoutes = require('./modules/grades/grade.routes');
const attendanceRoutes = require('./modules/attendance/attendance.routes');
const messageRoutes = require('./modules/messages/message.routes');
const notificationRoutes = require('./modules/notifications/notification.routes');
const absenceRoutes = require('./modules/absences/absence.routes');
const assignmentRoutes = require('./modules/assignments/assignment.routes');
const evaluationRoutes = require('./modules/evaluations/evaluation.routes');
const calendarRoutes = require('./modules/calendar/event.routes');
const roleRoutes = require('./modules/roles/role.routes');

module.exports = (app) => {
  app.use('/api/auth', authRoutes);
  app.use('/api/audit', auditRoutes);
  app.use('/api/schools', schoolRoutes);
  app.use('/api/superadmin', superAdminRoutes);
  app.use('/api/subscriptions', subscriptionRoutes);
  app.use('/api/students', studentRoutes);
  app.use('/api/classes', classRoutes);
  app.use('/api/subjects', subjectRoutes);
  app.use('/api/teachers', teacherRoutes);
  app.use('/api/parents', parentRoutes);
  app.use('/api/courses', courseRoutes);
  app.use('/api/schedule', scheduleRoutes);
  app.use('/api/rooms', roomRoutes);
  app.use('/api/grades', gradeRoutes);
  app.use('/api/attendance', attendanceRoutes);
  app.use('/api/messages', messageRoutes);
  app.use('/api/notifications', notificationRoutes);
  app.use('/api/absences', absenceRoutes);
  app.use('/api/justifications', absenceRoutes);
  app.use('/api/assignments', assignmentRoutes);
  app.use('/api/evaluations', evaluationRoutes);
  app.use('/api/competences', evaluationRoutes);
  app.use('/api/calendar', calendarRoutes);
  app.use('/api/roles', roleRoutes);
};
