const authRoutes = require('./modules/auth/auth.routes');
const auditRoutes = require('./modules/audit/audit.routes');
const schoolRoutes = require('./modules/schools/school.routes');
const superAdminRoutes = require('./modules/superadmin/superadmin.routes');
const subscriptionRoutes = require('./modules/subscriptions/subscription.routes');
const studentRoutes = require('./modules/students/student.routes');
const classRoutes = require('./modules/classes/class.routes');
const subjectRoutes = require('./modules/subjects/subject.routes');
const teacherRoutes = require('./modules/teachers/teacher.routes');
const parentRoutes = require('./modules/parents/parent.routes');
const courseRoutes = require('./modules/courses/course.routes');
const scheduleRoutes = require('./modules/schedules/schedule.routes');
const roomRoutes = require('./modules/rooms/room.routes');
const gradeRoutes = require('./modules/grades/grade.routes');
const attendanceRoutes = require('./modules/attendance/attendance.routes');
const messageRoutes = require('./modules/messages/message.routes');
const notificationRoutes = require('./modules/notifications/notification.routes');
const absenceRoutes = require('./modules/absences/absence.routes');
const assignmentRoutes = require('./modules/assignments/assignment.routes');
const evaluationRoutes = require('./modules/evaluations/evaluation.routes');
const competenceRoutes = require('./modules/evaluations/competence.routes');
const calendarRoutes = require('./modules/calendar/event.routes');
const roleRoutes = require('./modules/roles/role.routes');
const userRoutes = require('./modules/users/user.routes');
const invitationRoutes = require('./modules/invitations/invitation.routes');
const feeRoutes = require('./modules/fees/fee.routes');
const checkSubscription = require('./middlewares/checkSubscription.middleware');

module.exports = (app) => {
  app.use('/api/auth', authRoutes);
  app.use('/api/audit', auditRoutes);
  app.use('/api/schools', schoolRoutes);
  app.use('/api/superadmin', superAdminRoutes);
  app.use('/api/subscriptions', subscriptionRoutes);

  // 🔒 School Activity Routes (Require active subscription/status)
  app.use('/api/students', checkSubscription, studentRoutes);
  app.use('/api/classes', checkSubscription, classRoutes);
  app.use('/api/subjects', checkSubscription, subjectRoutes);
  app.use('/api/teachers', checkSubscription, teacherRoutes);
  app.use('/api/parents', checkSubscription, parentRoutes);
  app.use('/api/courses', checkSubscription, courseRoutes);
  app.use('/api/schedule', checkSubscription, scheduleRoutes);
  app.use('/api/rooms', checkSubscription, roomRoutes);
  app.use('/api/grades', checkSubscription, gradeRoutes);
  app.use('/api/attendance', checkSubscription, attendanceRoutes);
  app.use('/api/messages', checkSubscription, messageRoutes);
  app.use('/api/notifications', checkSubscription, notificationRoutes);
  app.use('/api/absences', checkSubscription, absenceRoutes);
  app.use('/api/assignments', checkSubscription, assignmentRoutes);
  app.use('/api/evaluations', checkSubscription, evaluationRoutes);
  app.use('/api/competences', checkSubscription, competenceRoutes);
  app.use('/api/calendar', checkSubscription, calendarRoutes);
  app.use('/api/roles', checkSubscription, roleRoutes);
  app.use('/api/users', checkSubscription, userRoutes);
  app.use('/api/invitations', checkSubscription, invitationRoutes);
  app.use('/api/fees', checkSubscription, feeRoutes);
};
