const authRoutes = require('./modules/auth/auth.routes');
const auditRoutes = require('./modules/audit/audit.routes');
const schoolRoutes = require('./modules/schools/school.routes');
const superAdminRoutes = require('./modules/superadmin/superadmin.routes');
const subscriptionRoutes = require('./modules/subscriptions/subscription.routes');
const studentRoutes = require('./modules/students/student.routes');
const classRoutes = require('./modules/classes/class.routes');
const subjectRoutes = require('./modules/subjects/subject.routes');
const teacherRoutes = require('./modules/teachers/teacher.routes');
const parentRoutes = require('./modules/parents/parent.routes');
const courseRoutes = require('./modules/courses/course.routes');
const scheduleRoutes = require('./modules/schedules/schedule.routes');
const roomRoutes = require('./modules/rooms/room.routes');
const gradeRoutes = require('./modules/grades/grade.routes');
const attendanceRoutes = require('./modules/attendance/attendance.routes');
const messageRoutes = require('./modules/messages/message.routes');
const notificationRoutes = require('./modules/notifications/notification.routes');
const absenceRoutes = require('./modules/absences/absence.routes');
const assignmentRoutes = require('./modules/assignments/assignment.routes');
const evaluationRoutes = require('./modules/evaluations/evaluation.routes');
const competenceRoutes = require('./modules/evaluations/competence.routes');
const calendarRoutes = require('./modules/calendar/event.routes');
const roleRoutes = require('./modules/roles/role.routes');
const userRoutes = require('./modules/users/user.routes');
const invitationRoutes = require('./modules/invitations/invitation.routes');
const feeRoutes = require('./modules/fees/fee.routes');
const expenseRoutes = require('./modules/expenses/expense.routes');
const financeRoutes = require('./modules/finance/finance.routes');
const paymentRoutes = require('./modules/payments/payment.routes');
const { protect } = require('./middlewares/auth.middleware');
const checkSubscription = require('./middlewares/checkSubscription.middleware');

module.exports = (app) => {
  app.use('/api/auth', authRoutes);
  app.use('/api/audit', auditRoutes);
  app.use('/api/schools', schoolRoutes);
  app.use('/api/superadmin', superAdminRoutes);
  app.use('/api/subscriptions', subscriptionRoutes);

  // 🔒 School Activity Routes (Require authentication AND active subscription/status)
  app.use('/api/students', protect, checkSubscription, studentRoutes);
  app.use('/api/classes', protect, checkSubscription, classRoutes);
  app.use('/api/subjects', protect, checkSubscription, subjectRoutes);
  app.use('/api/teachers', protect, checkSubscription, teacherRoutes);
  app.use('/api/parents', protect, checkSubscription, parentRoutes);
  app.use('/api/courses', protect, checkSubscription, courseRoutes);
  app.use('/api/schedule', protect, checkSubscription, scheduleRoutes);
  app.use('/api/rooms', protect, checkSubscription, roomRoutes);
  app.use('/api/grades', protect, checkSubscription, gradeRoutes);
  app.use('/api/attendance', protect, checkSubscription, attendanceRoutes);
  app.use('/api/messages', protect, checkSubscription, messageRoutes);
  app.use('/api/notifications', protect, checkSubscription, notificationRoutes);
  app.use('/api/absences', protect, checkSubscription, absenceRoutes);
  app.use('/api/assignments', protect, checkSubscription, assignmentRoutes);
  app.use('/api/evaluations', protect, checkSubscription, evaluationRoutes);
  app.use('/api/competences', protect, checkSubscription, competenceRoutes);
  app.use('/api/calendar', protect, checkSubscription, calendarRoutes);
  app.use('/api/roles', protect, checkSubscription, roleRoutes);
  app.use('/api/users', protect, checkSubscription, userRoutes);
  app.use('/api/invitations', protect, checkSubscription, invitationRoutes);
  app.use('/api/fees', protect, checkSubscription, feeRoutes);
  app.use('/api/expenses', protect, checkSubscription, expenseRoutes);
  app.use('/api/finance', protect, checkSubscription, financeRoutes);
  app.use('/api/payments', paymentRoutes);
};
