name: Shadow CI

on:
  push:
    branches: [ "main", "release" ]
    paths:
      - 'shadow/**'
      - '.github/workflows/shadow.yml'
  pull_request:
    branches: [ "main", "release" ]
    paths:
      - 'shadow/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./shadow

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: './shadow/package.json'

    - name: Install dependencies
      run: npm install

    # Add npm run test or npm run lint here if configured in package.json
    # - name: Run tests
    #   run: npm test
